include:
  - project: 'tmobile/suhwdev/firmware/gitlab-templates'
    file: '/gitlab-ci/.tmo.suhwdev.coding-guidelines.gitlab-ci.yml'
  - project: 'tmobile/suhwdev/firmware/gitlab-templates'
    file: '/gitlab-ci/.tmo.suhwdev.coding-guidelines-check-warns.gitlab-ci.yml'
  - project: 'tmobile/suhwdev/firmware/gitlab-templates'
    file: '/gitlab-ci/.tmo.suhwdev.compliance.gitlab-ci.yml'
  - project: 'tmobile/suhwdev/firmware/gitlab-templates'
    file: '/gitlab-ci/.tmo.suhwdev.compliance-check-warns.gitlab-ci.yml'
  - project: 'tmobile/suhwdev/firmware/gitlab-templates'
    file: '/gitlab-ci/.tmo.suhwdev.manual.native-posix-twister.gitlab-ci.yml'
  - project: 'tmobile/suhwdev/firmware/gitlab-templates'
    file: '/gitlab-ci/.tmo.suhwdev.git-merge.gitlab-ci.yml'

stages:
  - tmo
  - test

variables:
  ZEPHYR_BASE: ${CI_PROJECT_DIR}
  TMO_SECRETS_CHECK: 'False'
  MAIN_DEST_BRANCH: tmo-main
  MAIN_SRC_BRANCH: main
