#!/bin/sh

# adds any out of tree drivers built as modules to the zephyr build path


LOCATION=$(dirname $(realpath -s $BASH_SOURCE))

export ZEPHYR_EXTRA_MODULES=$LOCATION/drivers/sensor/tmp108/
export ZEPHYR_EXTRA_MODULES=$ZEPHYR_EXTRA_MODULES\;$LOCATION/drivers/modem/murata-1sc\;$LOCATION/drivers/wifi/rs9116w

#add lines as needed for each driver below

#export ZEPHYR_EXTRA_MODULES=$ZEPHYR_EXTRA_MODULES\;$LOCATION/drivers/(another driver here)
export ZEPHYR_EXTRA_MODULES=$ZEPHYR_EXTRA_MODULES\;$LOCATION/../wiseconnect-wifi-bt-sdk

echo $ZEPHYR_EXTRA_MODULES
